wagwan/posts/urls.py
from django.urls import path
from . import views


# POSTS URLS

app_name = 'posts'

urlpatterns = [
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('details/<int:pk>/', views.PostDetailView.as_view(), name='post_details'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('<str:category>/', views.CategoryPostListView.as_view(),
         name='category_posts'),
    path('posts/<int:pk>/comment/', views.add_comment_to_post,
         name='post_comment_list'),
    path('delete_comment/<int:pk>/',
         views.CommentDeleteView.as_view(), name='delete_comment'),
    path('comment/<int:pk>/reply/', views.reply_to_comment, name='reply'),


]

wagwan/wagwan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as account_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('welcome/', views.WelcomePage.as_view(), name='welcome'),
    path('bye/', views.ByePage.as_view(), name='bye'),
    path('profile/', account_views.Profile.as_view(), name='profile'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('update/<int:pk>/', account_views.UserUpdateView.as_view(),
         name='user_update'),
    path('image/', account_views.ImageUpdate,
         name='image_update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# TO BE REVIWED
# path('accounts/', include('django.contrib.auth.urls'))

wagwan/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from accounts.models import Profile
import misaka
from django.shortcuts import render

# POST MODELS


# ------------------------TAGS & CATEGORY MODELS-------------------------------#
class Tag(models.Model):
    """ To be worked  """
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    """ To be worked  """
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

# ------------------------POST  MODEL-------------------------------#


class Post(models.Model):

    CHOICES = (
        ('celebrate', 'celebrate'),
        ('planning', 'planning'),
        ('outdoor', 'outdoor'),
        ('holidays', 'holidays'),
        ('festivals', 'festivals'),
        ('movies', 'movies'),
        ('shopping', 'shopping'),
        ('laptop', 'laptop'),
        ('data', 'data'),
        ('science', 'science'),
        ('summers', 'summers'),
        ('medical', 'medical'),
        ('art', 'art'),

    )

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               default="")
    title = models.CharField(max_length=200)
    date_posted = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    category = models.CharField(max_length=100,
                                null=True, choices=CHOICES)
    tags = models.ManyToManyField(Tag)

    class Meta:
        """ Meta class to change the configuration,
        ordering by the given attribute"""
        ordering = ['-date_posted']

    def get_absolute_url(self):
        """ Reverse the Post object to the url once action
        has been taken with primary key to direct back to the
        same post """
        return reverse('posts:post_list')

    def __str__(self):
        return self.title

# ------------------------COMMENT MODEL-------------------------------#


class Comment(models.Model):
    """ comments for Post model  """

    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE,
                                     related_name='comment_for_post', null=True, default='')
    comment_text = models.TextField(null=True)
    date_posted = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        """ Reverse the Comment to the url once action
        has been taken with primary key to direct back to details page """
        return reverse('posts:post_details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.comment_text

# ------------------------ REPLY TO COMMENTS MODEL-------------------------------#


class Reply(models.Model):
    """ add reply to commnets """
    reply_comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, null=True, default='',
        related_name='comment_reply')
    reply_text = models.TextField()
    date_posted = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.reply_text

wagwan/posts/forms.py
from django import forms
from . import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'text', 'category')
        model = models.Post


class TagForm(forms.ModelForm):
    class Meta:
        fields = ('name',)
        model = models.Tag


class CommentForm(forms.ModelForm):
    class Meta:
        fields = ('comment_text',)
        model = models.Comment


class ReplyCommentForm(forms.ModelForm):
    class Meta:
        fields = ('reply_text',)
        model = models.Reply

wagwan/posts/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.shortcuts import render, redirect
from shapeshifter.views import MultiFormView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from . import forms
from . import models

# POSTS VIEWS


# ------------------------POST  VIEWS ------------------------------#

class PostCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = forms.PostForm
    template_name = 'posts/post_form.html'

    def form_valid(self, form):
        """ function will set the author name automatically to the
        user logged in when post.author is passed inside the template """

        form.instance.author = self.request.user
        return super().form_valid(form)


class PostListView(LoginRequiredMixin, generic.ListView):
    model = models.Post
    paginate_by = 7


class UserPostListView(LoginRequiredMixin, generic.ListView):
    """ class will display posts from the selected user """
    model = models.Post
    template_name = 'posts/user_post.html'
    paginate_by = 7

    def get_queryset(self):
        """ self.kwargs.get method will get the username form the URL
        - see the url for this class """
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return models.Post.objects.filter(author=user)


class CategoryPostListView(LoginRequiredMixin, generic.ListView):
    """ class to display posts from selected category """
    model = models.Category
    template_name = 'posts/category_post.html'
    paginate_by = 7

    def get_queryset(self):
        """ self.kwargs.get method will get the username form the URL
        - see the url for this class """
        cat = models.Post.objects.filter(category=self.kwargs.get('category'))
        return cat


class PostDetailView(LoginRequiredMixin, generic.DetailView):
    """ class to display posts in detail """
    model = models.Post


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    """ class to update the post """
    fields = ('title', 'text')
    model = models.Post

    def form_valid(self, form):
        """ function will set the author name automatically to the
        user logged in when post.author is passed inside the template """
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        """ func will prevent current user to update other users post """
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    """ class to delete the post """
    model = models.Post
    success_url = reverse_lazy('posts:post_list')

    def test_func(self):
        """ func will prevent current user to delete other users post """
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# ------------------------COMMENT VIEWS-------------------------------#


# class CommentPostView(LoginRequiredMixin, generic.CreateView):
#     form_class = forms.CommentForm
#     template_name = 'posts/post_comment.html'
#
#     def form_valid(self, form):
#         form.instance.comment_text = self.request.user
#         return super().form_valid(form)


@login_required
def add_comment_to_post(request, pk):
    """ To attach comments to the post"""
    post = get_object_or_404(models.Post, pk=pk)

    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        form.instance.author = request.user

        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_post = post
            comment.save()
            return redirect('posts:post_details', pk=post.pk)

    else:
        form = forms.CommentForm()

    return render(request, 'posts/comment_form.html', context={'form': form})


class CommentDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Comment
    template_name = 'posts/comment_confirm_delete.html'

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        super().delete(*args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('posts:post_details', kwargs={'pk': self.object.comment_post.id})

    # def test_func(self):
    #     """ func will prevent current user to delete other users post """
    #     post = self.get_object()
    #     if self.request.user == post.author:
    #         return True
    #     return False


# ------------------------REPLY COMMENT VIEWS-------------------------------#

@login_required
def reply_to_comment(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)

    if request.method == 'POST':
        reply_form = forms.ReplyCommentForm(request.POST)

        if reply_form.is_valid():
            reply = reply_form.save(commit=False)
            reply.reply_comment = comment
            reply.save()
            return redirect('posts:post_details', pk=comment.pk)

    else:
        reply_form = forms.ReplyCommentForm()

    return render(request, 'posts/reply_comment_form.html', context={'reply_form': reply_form})

wagwan/posts/templates/posts/category_post.html
{% extends 'posts/posts_base.html' %}
{% block content %}


{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static '/css/posts_styles.css' %}">


<div class="container post-list">
    <div class=" w-50">
        <div class="content-section">
          <div class="media">

            <div class="media-body">
              <h4  class="account-heading mt-3 post-list-title">Category: {{view.kwargs.category}}</h4>
              <hr>
            </div>
          </div>

        {% for post in post_list %}

        <div class = 'border border-bottom mb-2 bg-light'>
            <ul>
                <h4>
                    <a class = 'post-list-title' href="{% url 'posts:post_details' post.id %}">{{post.title}}</a>
                </h4>
                <p class=' mr:2'>
                    <a class ='text-capitalize post-list-title' href="{% url 'posts:user_posts' post.author.username %}">
                         {{post.author}}</a>
                        <span style = 'font-size:10px;'> Date: {{post.date_posted|date:"d-M-Y"}}</span>

                 </p>
            </ul>
        </div>
        {% endfor %}



         <div class="paginator" >

        {% if is_paginated  %}

        {% if page_obj.has_previous %}
        <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar'  href="?page=1">First</a>
        <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num  %}
        <a class=' btn btn-info btn-sm mb-4 paginator-current-bar' href="?page={{num}}">{{ num }}</a>

        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{num}}">{{num}}</a>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{page_obj.next_page_number}}">Next</a>
        <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{page_obj.paginator.num_pages}}">Last</a>
        {% endif %}

        {% endif %}
        </div>

    </div>

</div>

{% endblock %}

wagwan/posts/templates/posts/comment_confirm_delete.html
{% extends 'posts/posts_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class = 'container mt-4'>
    <h2>Are you sure, you want to delete the comment?</h2>
<form  method="POST">

    {% csrf_token %}
    {{ form|crispy }}
    <input class = ' btn btn-outline-danger btn-sm mt-4' type="submit" name="" value="Yes, sure">
    <a class = 'btn btn-outline-primary btn-sm mt-4 ml-2' href="{% url 'posts:post_details' object.comment_post.id %}">Cancel</a>

</form>

</div>

{% endblock %}

wagwan/posts/templates/posts/comment_form.html
{% extends 'posts/posts_base.html' %}
{% load crispy_forms_tags %}
{% block content %}


{% load static %}


<form class=""  method="POST">

    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" name="" value="Post">



</form>





{% endblock %}

wagwan/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/posts_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5">

<h2>Are you sure you want to delete:  {{post.title}}?</h2>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input class = ' btn btn-outline-danger btn-sm mt-4' type="submit" value="Yes, sure">
    <a class = 'btn btn-outline-primary btn-sm mt-4 ml-2' href="{% url 'posts:post_details' post.id %}">Cancel</a>

</form>


</div>


{% endblock content %}

wagwan/posts/templates/posts/post_detail.html
{% extends 'posts/posts_base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/posts_styles.css' %}">

<div class="container">
    <div class="post-detail container">
        <h1 class='mt-2 mb-0'>{{object.title}}
            <span style='font-size:15px;'>
                <u>
                    <!--To check if the current user is logged in & only current user can see the
                    updated or delete options -->

                    {% if object.author == user %}
                    <a class='text-primary ml-3' href="{% url 'posts:post_update' object.id %}">Update</a>
                    <a class='text-danger ml-2' href="{% url 'posts:post_delete' post.id %}">Delete</a>
                    {% endif %}

                </u>
            </span>
        </h1>
        <hr>
        <p class='mb-5'>{{ object.text}}</p>
        <hr>
    </div>
    <div class="container">
        <a  href="{% url 'posts:post_comment_list' post.id %}"> <span><b><u>Comment</u></b></span></a>
    </div>



    <!--COMMNET SECTION -->

    <div class='container'>
      {% for comment in post.comment_for_post.all %}
      <br>
      {% if  object.author == user %}
      <div class="comment-post">
          <ul>
              <li>
                  <p >{{comment.comment_text|safe}}. <span><a class = 'comment-links' href="{% url 'posts:reply' object.id %}"> Reply</a></span></p>
                  <p class='text-capitalize'>From {{user.username}} on {{comment.date_posted|date:'d-M-y'}}.
                      <span><a class = 'comment-links' href="{% url 'posts:delete_comment' comment.id %}">Delete comment?</a></span>
                  </p>
              </li>
          </ul>

          </div>
          {%else %}
          <div class="comment-post">
          <ul>
              <li>
                  <p >{{comment.comment_text|safe}}. <span><a class = 'comment-links' href="{% url 'posts:reply' object.id %}"> Reply</a></span></p>
                  <p class='text-capitalize' >From {{user.username}} on {{comment.date_posted|date:'d-M-y'}}.</p>
              </li>
          </ul>
          {% endif %}
          {% endfor %}
          </div>

          <!--REPLY TO COMMNET SECTION-->


            {% for reply in comment.comment_reply.all %}
            <br>
            {% if comment %}

            <div class="">
                <ul>
                    <li>
                        <p >{{reply.reply_text}} </p>
                        <p class='text-capitalize'>From {{user.username}} on {{comment.date_posted|date:'d-M-y'}}.</p>
                    </li>
                </ul>
                </div>
                {%else %}
                <div class="">

                    <ul>
                        <li>
                            <p >{{reply.reply_text|safe}}</p>
                            <p class='text-capitalize'>From {{user.username}} on {{comment.date_posted|date:'d-M-y'}}.</p>
                        </li>
                    </ul>

                {% endif %}
                {% endfor %}
                </div>




    {% endblock content %}

wagwan/posts/templates/posts/post_form.html
{% extends 'posts/posts_base.html' %}
{%  load crispy_forms_tags %}
{% block content %}

<div class="post-create container">
    <form class="form-horizontal w-50" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Post">
    </form>
</div>
{% endblock content %}

wagwan/posts/templates/posts/post_list.html
{% extends 'posts/posts_base.html' %}
{% block content %}


{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/posts_styles.css' %}">





<div class="container post-list">
    <div class=" w-50">
        <div class="content-section">
            <div class="media">
                <div class="media-body">
                    <p class="account-heading mt-3 post-list-title">The owner of the website takes no responsiblities for any of the blog.</p>
                    <hr>
                </div>
            </div>



            {% for post in post_list %}

            <div class='border border-bottom mb-2 bg-light'>
                <ul>
                    <h5>
                        <a class='post-list-title' href="{% url 'posts:post_details' post.id %}">{{post.title}}</a>
                    </h5>
                    <p class=' post-list-link mr:2'>
                        <a class='text-capitalize post-list-title' href="{% url 'posts:user_posts' post.author.username %}">
                            <span class='text-muted'>Author: </span>{{post.author}},</a>
                        <a href="{% url 'posts:category_posts' post.category %}">
                            <span class='text-muted'>Category: </span>{{post.category}},</a>
                        <span> Date: {{post.date_posted|date:"d-M-Y"}}</span>
                    </p>
                </ul>
            </div>
            {% endfor %}







            <div class="paginator">

                {% if is_paginated  %}

                {% if page_obj.has_previous %}
                <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page=1">First</a>
                <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{page_obj.previous_page_number}}">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num  %}
                <a class=' btn btn-info btn-sm mb-4 paginator-current-bar' href="?page={{num}}">{{ num }}</a>

                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{num}}">{{num}}</a>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{page_obj.next_page_number}}">Next</a>
                <a class=' btn btn-outline-info btn-sm mb-4 paginator-bar' href="?page={{page_obj.paginator.num_pages}}">Last</a>
                {% endif %}

                {% endif %}
            </div>

        </div>
    </div>

    {% endblock %}

wagwan/posts/templates/posts/posts_base.html
{% extends 'base.html'%}
{% load static %}
<link rel="stylesheet" href="{% static 'css/posts_styles.css' %}">


<div class="container">
    {% block content %}
    {% endblock content%}

</div>

wagwan/posts/templates/posts/reply_comment_form.html
{% extends 'posts/posts_base.html' %}
{% block content %}
{%  load crispy_forms_tags %}

<div class="container mt-2">
    <form class=""  method="POST">
        {% csrf_token %}
        {{reply_form|crispy}}
        <input type="submit" value="Reply">
    </form>
</div>




{% endblock %}

wagwan/posts/templates/posts/user_post.html
{% extends 'posts/posts_base.html'%}
{% block content %}


<div class="container post-list">
    <div class=" w-50">
        <div class="content-section">
          <div class="media">
            <div class="media-body">
              <h4 class="account-heading mt-3 text-capitalize">Author:  {{view.kwargs.username}} ({{ page_obj.paginator.count}})</h4>
              <hr>
            </div>
          </div>

        {% for post in post_list %}

        <div class = 'border border-bottom mb-2 bg-light'>
            <ul>
                <h4>
                    <a href="{% url 'posts:post_details' post.id %}">{{post.title}}</a>
                </h4>
                <p class=' mr:2 text-capitalize'>
                    {{post.author}}, <span style = 'font-size:10px;'> Date: {{post.date_posted|date:"d-M-Y"}}</span>
                </p>
            </ul>
        </div>
        {% endfor %}

        {% if is_paginated %}

        {% if page_obj.has_previous %}
        <a class=' btn btn-outline-info mb-4' href="?page=1">First</a>
        <a class=' btn btn-outline-info mb-4' href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num  %}
        <a class=' btn btn-info mb-4' href="?page={{num}}">{{ num }}</a>

        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class=' btn btn-outline-info mb-4' href="?page={{num}}">{{num}}</a>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a class=' btn btn-outline-info mb-4' href="?page={{page_obj.next_page_number}}">Next</a>
        <a class=' btn btn-outline-info mb-4' href="?page={{page_obj.paginator.num_pages}}">Last</a>
        {% endif %}

        {% endif %}

    </div>

</div>

{% endblock %}