wagwan/accounts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete')


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wagwan/posts/urls.py
from django.urls import path
from . import views


# POSTS URLS

app_name = 'posts'

urlpatterns = [
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('details/<int:pk>/', views.PostDetailView.as_view(), name='post_details'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('<str:category>/', views.CategoryPostListView.as_view(),
         name='category_posts'),
    path('posts/<int:pk>/comment/', views.add_comment_to_post,
         name='post_comment_list'),
    path('delete_comment/<int:pk>/',
         views.CommentDeleteView.as_view(), name='delete_comment'),
    path('comment/<int:pk>/reply/', views.reply_to_comment, name='reply'),


]

wagwan/wagwan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as account_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('welcome/', views.WelcomePage.as_view(), name='welcome'),
    path('bye/', views.ByePage.as_view(), name='bye'),
    path('profile/', account_views.Profile.as_view(), name='profile'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('update/<int:pk>/', account_views.UserUpdateView.as_view(),
         name='user_update'),
    path('image/', account_views.ImageUpdate,
         name='image_update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# TO BE REVIWED
# path('accounts/', include('django.contrib.auth.urls'))

wagwan/templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <h3 class = 'mt-3'>Information about waGwan</h3>
    <hr>
    <ul>
        <li><p>This company was initally found in Dec 2021.</p></li>
        <li><p>Contact raw@gmail.com for more information.</p></li>
    </ul>

</div>

{% endblock content %}

wagwan/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title></title>

    <!-- BOOTSTARP -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- GOOGLE FONTS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- CSS STYLES -->

    <link rel="stylesheet" type="text/css"   href="{% static '/css/master.css' %}">


</head>

<body>


    <nav class="navbar navbar-expand-md navbar-dark" style='background-color:#3e515e;' >
        <b> <a href="{% url 'home' %}" class="navbar-brand ">waGwan
            <span class = 'base-wagwan text-capitalize'>{{user.username}}</span>
        </a></b>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'about'%}">About </a><span class="sr-only"></span></a>
                </li>

            </ul>
            {# RIGHT SIDE OF THE NAVBAR #}
            {% if user.is_authenticated %}

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a><span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create'%}">New post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:post_list' %}">Post list</a>
                        </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
            </ul>

             {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>


</body>
<!-- JAVASCRIPT -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



<div class="container">
    {% block content %}

    {% endblock content %}

</div>

</html>

wagwan/templates/bye.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Bye</title>

        <div class = 'jumbotron'>
            <h2>Thanks for visting. See you soon!</h2>
        </div>
    </head>
    <body>

    </body>
</html>

wagwan/templates/home.html
{% extends 'base.html' %}

{% block content %}


<main role="main" class="container">
    <div class="">
    </div>
    <div class="row">
        <div class="col-md-8">
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Quick Sidebar</h3>
                <p class='text-muted '>click on the link to access the page.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">
                        <a href="{% url 'posts:post_list' %}">Post List</a>
                    </li>
                    <li class="list-group-item list-group-item-light">
                        <a href="{% url 'posts:create'%}">Create Post</a>
                    </li>
                    <li class="list-group-item list-group-item-light">
                        <a href="#">Upcoming Events</a>
                    </li>
                    <li class="list-group-item list-group-item-light">
                        <a href="#">etc</a>

                    </li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</main>



{% endblock content %}

wagwan/templates/profile.html
{# {% extends 'base.html'%}

{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="userimage.jpg">
    <div class="media-body">
      <h2 class="account-heading">{{user.username}}</h2>
      <p class="text-secondary">{{user.email}}</p>
    </div>
  </div>
  <!-- FORM HERE -->
</div>

</div>

{% endblock content %} #}

wagwan/templates/welcome.html
{% extends 'base.html' %}
{% block content %}

<div class='home-page container-fluid'>
    <h2>Welcome {{user.username}} </h2>

</div>



{% endblock content %}