wagwan/accounts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete')


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wagwan/posts/urls.py
from django.urls import path
from . import views


# POSTS URLS

app_name = 'posts'

urlpatterns = [
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('details/<int:pk>/', views.PostDetailView.as_view(), name='post_details'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('<str:category>/', views.CategoryPostListView.as_view(),
         name='category_posts'),
    path('posts/<int:pk>/comment/', views.add_comment_to_post,
         name='post_comment_list'),
    path('delete_comment/<int:pk>/',
         views.CommentDeleteView.as_view(), name='delete_comment'),
    path('comment/<int:pk>/reply/', views.reply_to_comment, name='reply'),


]

wagwan/wagwan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as account_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('welcome/', views.WelcomePage.as_view(), name='welcome'),
    path('bye/', views.ByePage.as_view(), name='bye'),
    path('profile/', account_views.Profile.as_view(), name='profile'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('update/<int:pk>/', account_views.UserUpdateView.as_view(),
         name='user_update'),
    path('image/', account_views.ImageUpdate,
         name='image_update'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


# TO BE REVIWED
# path('accounts/', include('django.contrib.auth.urls'))

wagwan/accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image

from django_resized import ResizedImageField

# ACCOUNTS MODELS


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, default="")
    # image = models.ImageField(default='default.jpeg', upload_to='profile_pics')
    image = ResizedImageField(
        size=[100, 100], crop=['middle', 'center'], upload_to='profile_pics', default='default.jpeg')

    def __str__(self):
        return f"{self.user.username} Profile"

    # ------ANOTHER WAY OF RESIZING THE IMAGE -----#

    # def save(self, *args, **kwargs):
    #     super(Profile, self).save(*args, **kwargs)
    #     img = Image.open(self.image.path)
    #     if img.height > 150 or img.width > 150:
    #         output_size = (150, 150)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

wagwan/accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from . import models

# ACCOUNTS FORMS


class UserSignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email')


class ImageUpdateForum(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('image',)

wagwan/accounts/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        UserPassesTestMixin)

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

from django.shortcuts import render, redirect
from django.contrib import messages
from . import models

from . import forms


# ACCOUNTS VIEW


class LoginPage(generic.CreateView):
    pass


class SignUp(generic.CreateView):

    form_class = forms.UserSignupForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


class Profile(generic.TemplateView):
    model = models.Profile
    template_name = 'accounts/profile.html'


class UserUpdateView(generic.UpdateView):

    fields = ('username', 'email')
    model = User
    template_name = 'accounts/profile_form.html'

    def get_success_url(self):
        return reverse('profile')


def ImageUpdate(request):
    profile = request.user.profile
    image_form = forms.ImageUpdateForum(instance=profile)
    if request.method == "POST":

        image_form = forms.ImageUpdateForum(
            request.POST, request.FILES, instance=profile)

        if image_form.is_valid():
            image_form.save()

    context = {'image_form': image_form}
    return render(request, 'accounts/profile.html', context)


# def profile(request):
#     u_form = forms.UserUpdateForm(instance=request.user)
#     p_form = forms.ImageUpdateForum(instance=request.user.profile)
#     if request.method == "POST":
#
#         u_form = forms.UserUpdateForm(request.POST, instance=request.user)
#
#         p_form = forms.ImageUpdateForum(
#             request.POST, request.FILES, instance=profile)
#
#         if p_form.is_valid() and u_form.is_valid():
#             p_form.save()
#             u_form.save()
#             messages.success(request, 'Your profile has been updated')
#             return redirect('profile')
#
#     context = {
#         'u_form': u_form,
#         'p_form': p_form
#     }
#     return render(request, 'profile.html', context)

wagwan/accounts/templates/accounts/accounts_base.html
{% extends 'wagwan/base.html' %}

{% load static %}

<link rel="stylesheet" href="{% static 'accounts/css/styles.css' %}">
{% block content %}
{% endblock content %}

wagwan/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}


<div class = 'container'>

<form class = 'form-horizontal' method = 'POST'>
    {% csrf_token %}
    {{form|crispy }}
    <input class = 'btn btn-outline-primary btn-sm'  type="submit" value= 'Login'>
    <small class ='text text-muted ml-2'>
        <a href="{% url 'accounts:password_reset' %}">Forgot password?</a>
    </small>


</form>

</div>
{% endblock %}

wagwan/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<div class = 'container'>

<form class = 'form-horizontal w-50' method = 'POST'>
    {% csrf_token %}
    {{form|crispy }}

    <input class = 'btn btn-outline-primary btn-sm'  type="submit" value= 'Request password'>

</form>

</div>
{% endblock %}

wagwan/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% block content %}


<div class = 'container'>

<h4 class = 'alert alert-info'>
    We have emailed you the link to reset your password
</h4>
</div>
{% endblock %}

wagwan/accounts/templates/accounts/profile.html
{% extends 'base.html'%}
{% load crispy_forms_tags%}
{% block content %}


<div class="content-section mt-3 w-50">
    <div class="media">
        <img class="rounded-circle account-img mr-3 " src="{{request.user.profile.image.url}}">
        <div class="media-body">

            <form enctype="multipart/form-data" action="{% url 'image_update'  %}" method="post">

                <h2 class="account-heading text-capitalize">{{user.username}}</h2>
                <p class="text-secondary">{{user.email}}
                    {% csrf_token %}
                    {{image_form|crispy}}
                    {{ form|crispy }}
                    <span class='btn btn-outline-primary btn-sm ' style='font-size:12px'> <a href="{% url 'user_update' user.id %}">Info</a> </span>
                    <button class='btn btn-outline-primary btn-sm border:none' type="submit">Image</button>

            </form>
            </p>
            <hr>
        </div>
    </div>
    <!-- FORM HERE -->

</div>

{% endblock content %}

wagwan/accounts/templates/accounts/profile_form.html
{% extends 'base.html'%}
{% load crispy_forms_tags%}

{% block content %}

  <!-- FORM HERE -->
  <div class="container">
              <form method="post">
                  {% csrf_token %}
                  {{ form|crispy }}
          <input class ='btn btn-outline-primary btn-sm  mt-3' type="submit" name="" value="Update">
      </form>
  </div>

{% endblock content %}

wagwan/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = 'container'>

    <form class = 'forms-horizontal' method = 'POST'>
       {% csrf_token %}
       {{ form|crispy }}
       <input type="submit" class = "btn btn-default" value ="Signup">
    </form>


</div>

{% endblock content %}